name: WebGoat 

on: 
  push:
      branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3

      - name: "Instalacion de Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"    
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target

      - name: "Crear imagen de Docker"
        run: docker build -t webgoat ./

      - name: "Verificar imagen"
        run: docker images 

      - name: "Configurar las credenciales AWS"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: "Cargar imagen a ECR"
        run: |
              aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n3j7o1e0
              docker build -t fernandagarcia .
              docker tag fernandagarcia:latest public.ecr.aws/n3j7o1e0/fernandagarcia:latest
              docker push public.ecr.aws/n3j7o1e0/fernandagarcia:latest

      - name: "Aprovisionar terraform"
        run: |
              terraform -chdir=terraform/ init
              terraform -chdir=terraform/ validate
              terraform -chdir=terraform/ plan -out tfplan
              terraform -chdir=terraform/ apply tfplan

      #- name: "Descargar arachni"
       # run: |
        #      wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
         #     tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
      
 
 
      #- name: "Ejecutar arachni"
       # run: |
        #      var_IP=$(docker inspect container-prueba | grep "IPAddress" | tail -1 | cut -d '"' -f 4)
         #     ./arachni-1.6.1.3-0.6.1.1/bin/arachni --check=* http://$var_IP:8080/WebGoat/login
      


 

  